chore/JSSNMSHDD-2541 initialize
nmshd/cns-consumption pull request #1
Opened 2021-09-27 14:24 UTC by jkoenig134

2021-09-27 14:36 UTC, tnotheis requested changes

2021-09-27 14:36 UTC, tnotheis commented on .gitignore
> +.nyc_output
Hier auch mal aufräumen, oder?

2021-09-27 14:36 UTC, tnotheis commented on .prettierignore
> +node_modules
newline

2021-09-27 14:36 UTC, tnotheis commented on nbt.json
> +                "nmshd.core.js",
core => transport

2021-09-27 14:36 UTC, tnotheis commented on nbt.json
> +                "nmshd.core.min.js",
core => transport

2021-09-28 05:48 UTC, tnotheis requested changes

2021-09-28 05:48 UTC, tnotheis commented on .github/workflows/publish.yml
> +          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
Nenn die Variable doch einfach nur BUILD_NUMBER. Dem Script sollte es egal sein, ob die Build Number von Bitbucket oder von GitHub kommt.

2021-09-28 05:48 UTC, tnotheis commented on .ci/writeBuildInformation.sh
> +#!/usr/bin/env bash
Wie in Teams besprochen: wir sollten in dieses Script noch eine Art Validierung einbauen, um zu überprüfen, ob das, was wir da reinschreiben, auch wirklich sinnvoll ist.

2021-09-28 05:48 UTC, tnotheis commented on .github/workflows/test.yml
> +          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
Auch hier: BUILD_NUMBER anstatt GITHUB_BUILD_NUMBER

2021-09-28 06:45 UTC, tnotheis requested changes

2021-09-28 06:45 UTC, tnotheis commented on .ci/runChecks.sh
> +npm audit
Newline ;-)

2021-09-28 06:45 UTC, tnotheis commented on .github/workflows/publish.yml
> +          registry-url: https://registry.npmjs.org/
Warum brauchst du das? Ist doch bestimmt Default

2021-09-28 06:46 UTC, jkoenig134 commented on .github/workflows/publish.yml
> +          registry-url: https://registry.npmjs.org/
Hm, ja.. haben wir halt überall so

2021-09-28 06:47 UTC, jkoenig134 commented on .github/workflows/publish.yml
> +          registry-url: https://registry.npmjs.org/
Hatte auch mal gelesen und keine defaults gefunden

2021-09-28 06:53 UTC, tnotheis approved these changes

2021-09-28 06:55 UTC, merged