Feature/implement freetext request item
nmshd/cns-consumption pull request #108
Opened 2023-08-03 14:29 UTC by vinzlange

2023-08-03 14:41 UTC, jkoenig134 commented on .ci/runChecks.sh
> +npx better-npm-audit audit --exclude 1092593
can you instead resolve this vulnerability with `npm audit fix`?

2023-08-03 14:41 UTC, jkoenig134 commented on src/modules/requests/itemProcessors/freetextAttribute/FreetextRequestItemProcessor.ts
> +        return FreetextAcceptResponseItem.from({
as discussed the processor isn't currently doing anything - that will be changed.

2023-08-03 15:21 UTC, jkoenig134 requested changes

2023-08-03 15:21 UTC, jkoenig134 commented on src/modules/requests/itemProcessors/freetextAttribute/FreetextRequestItemParameters.ts
> +export interface FreetextRequestItemParametersJSON {
```suggestion
export interface FreetextRequestItemParametersJSON extends AcceptRequestItemParametersJSON {
```

2023-08-03 15:58 UTC, jkoenig134 commented on src/modules/requests/itemProcessors/freetextAttribute/FreetextRequestItemParameters.ts
> +export interface FreetextRequestItemParametersJSON extends AcceptRequestItemParametersJSON {
aren't this accept params?

2023-08-03 16:00 UTC, jkoenig134 commented on src/modules/requests/itemProcessors/freetextAttribute/FreetextRequestItemParameters.ts
> +export interface FreetextRequestItemParametersJSON extends AcceptRequestItemParametersJSON {
i think it should be called `AcceptFreetextRequestItemParametersJSON`. but look at the other params before changing it.

2023-08-09 06:09 UTC, jkoenig134 commented on src/modules/requests/index.ts
> +export * from "./itemProcessors/freeTextAttribute/FreeTextRequestItemProcessor"
```suggestion
export * from "./itemProcessors/freeText/FreeTextRequestItemProcessor"
```
that item isn't related to an attribute -> createAttribute is for the CreateAttributeRequestItem

2023-08-09 06:12 UTC, jkoenig134 requested changes

2023-08-09 06:12 UTC, jkoenig134 commented on src/modules/requests/itemProcessors/freeTextAttribute/FreeTextRequestItemParameters.ts
> +    public freetext: string
```suggestion
    public freeText: string
```

2023-08-09 06:12 UTC, jkoenig134 commented on src/modules/requests/itemProcessors/freeTextAttribute/FreeTextRequestItemParameters.ts
> +    freetext: string
```suggestion
    freeText: string
```

2023-08-09 06:13 UTC, jkoenig134 commented on src/modules/requests/itemProcessors/freeTextAttribute/FreeTextRequestItemParameters.ts
filename.. AcceptFreeTextRequestItemParameters

2023-08-09 07:02 UTC, jkoenig134 commented
the only missing thing is a test for the new processor. Should be quite easy as only the accept method is implemented.

Additionally you should implement the canAccept method to check if the params are correct.

And you forgot to add the Accept Params to the barrel export (index.ts).

2023-08-09 14:24 UTC, jkoenig134 approved these changes

2023-08-09 14:24 UTC, jkoenig134 commented
@tnotheis FYI.

2023-08-10 06:18 UTC, merged

2023-08-23 11:02 UTC, tnotheis commented on test/modules/requests/itemProcessors/freeText/FreeTextRequestItemProcessor.test.ts
> +                    expect(result).to.be.an.errorValidationResult()
You should check the error code. (it may be that there is an overload of the `errorValidationResult` method that does that check)

2023-08-23 11:02 UTC, tnotheis commented on test/modules/requests/itemProcessors/freeText/FreeTextRequestItemProcessor.test.ts
> +                ;({ consumptionController } = account)
This is really hard to read. Shouldn't it be equivalent to 

```ts
consumptionController = account.consumptionController;
```
?

2023-08-23 11:04 UTC, jkoenig134 commented
@vinzlange Timos comments are valid. Please rework it.