Feature/dev 5642 attribute controller succeed attribute methods
nmshd/cns-consumption pull request #111
Opened 2023-09-05 07:34 UTC by J-Gann

2023-10-23 13:47 UTC, jkoenig134 requested changes

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/local/CreateLocalAttributeParams.ts
this is a wild mix of optional + nullable combinations:

- optional + nullable
- only optional
- only nullable

typically we write nullable like this:
```ts
@serialize()
@validate({ nullable: true })
```

2023-10-23 13:47 UTC, jkoenig134 commented on .vscode/settings.json
should be returned to our project standard

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/events/AttributeSucceededEvent.ts
See e.G. `src/modules/requests/events/IncomingRequestStatusChangedEvent.ts` on how to do payload with more than one parameter.

You can leave multiple params in the ctor, but the data has to be an object. With the current approach it's way to hard to understand which one is the predecessor und which the successor.

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/local/LocalAttribute.ts
> +    public isPeerSharedAttribute(expectedPeer?: CoreAddress): boolean {
why isn't this a typeguard?

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/local/LocalAttributeShareInfo.ts
>      requestReference: string
I dont't like this approach. We can be backwards compatible without having a confusing naming.

I'd suggest making requestReference optional and adding another optional notificationReference. And then make serval validate that requestReference or notificationReference must be set.

@tnotheis @stnmtz veto or other thoughts?

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/attributeSucceeded/AttributeSucceededNotificationItemProcessor.ts
> +    ): Promise<boolean> {
Maybe we should return a validation result here. There are no logs / indicators on what's wrong.

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/attributeSucceeded/AttributeSucceededNotificationItemProcessor.ts
> + */
explaining the name of the class in other words. IMO we don't need such comments.

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/attributeSucceeded/AttributeSucceededNotificationItemProcessor.ts
> +        }
wtb moving the logic in rollback and using rollback in the catch?

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/attributeSucceeded/AttributeSucceededNotificationItemProcessor.ts
> +            await this.rollbackPartialWork(notificationItem, notification)
missing error handing (just add a .catch and log if an error occurs)

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/attributeSucceeded/AttributeSucceededNotificationItemProcessor.ts
> +            await this.consumptionController.attributes.deleteAttributeUnsafe(successor.id)
missing error handing (just add a .catch and log if an error occurs)

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/attributeSucceeded/AttributeSucceededNotificationItemProcessor.ts
> +            await this.consumptionController.attributes.updateAttributeUnsafe(
missing error handing (just add a .catch and log if an error occurs)

2023-10-23 13:47 UTC, jkoenig134 commented on test/modules/notifications/TestNotificationItem.ts
can be deleted. there is already the same class in `test/modules/notifications/testHelpers/TestNotificationItem.ts`

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +import { AttributeCreatedEvent, AttributeDeletedEvent, SharedAttributeCopyCreatedEvent } from "./events"
what am I missing, why don't we have an `AttributeSucceededEvent` anymore?

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +}
should not be in this file - and where is the class for this?

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +     */
can be removed

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +     */
this comment is needed at every isolated method (or nowhere), or I have to jump around and look "when this comment ends".

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +     */
useless, all these information is in the name of the methods

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +            predecessor.shareInfo.sourceAttribute === undefined
these comments should be variables. e.g. ->

```suggestion
        const predecessorIsOwnSharedIdentityAttribute = !predecessor.isIdentityAttribute() ||
            !predecessor.isOwnSharedAttribute(this.identity.address) ||
            predecessor.shareInfo.sourceAttribute === undefined
        if (predecessorIsOwnSharedIdentityAttribute) {
```

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +            successor.shareInfo.sourceAttribute === undefined
We do not use `=== undefined`. Instead `typeof {variable} === "undefined"`. You should check this everywhere, I'll not comment this again.

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +     */
is already descriptive enough in the method names.

2023-10-23 13:47 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
>      }
you can compare the prototypes instead

2023-10-23 13:57 UTC, tnotheis commented on src/modules/attributes/local/LocalAttributeShareInfo.ts
>      requestReference: string
I agree.

2023-10-24 06:09 UTC, jkoenig134 commented on .vscode/settings.json
we can discuss this outside of the PR, but for now we don't change the project defaults.

2023-10-24 06:09 UTC, jkoenig134 commented on src/modules/attributes/events/AttributeSucceededEvent.ts
yeah, thats fine

2023-10-24 06:10 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/attributeSucceeded/AttributeSucceededNotificationItemProcessor.ts
> +    ): Promise<boolean> {
I know, but I didn't want to get this lost.

2023-10-24 06:14 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/attributeSucceeded/AttributeSucceededNotificationItemProcessor.ts
> + */
I think this is implicit. You can not succeed an Attribute that wasn't shared before over a Notification.

2023-10-24 06:15 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/attributeSucceeded/AttributeSucceededNotificationItemProcessor.ts
> +        }
I see no problem with calling rollback when it is safe.

Bit if you insist you can also just name the private method _rollback and remove that comment.

2023-10-24 06:19 UTC, jkoenig134 commented on test/modules/notifications/attributeSucceeded/AttributeSucceededNotificationItemProcessor.test.ts
> +            it("Happy path for a peer shared identity attribute", async function () {
1. nope, you have here one test with three stages, but a test should only contain one. That should be reworked. Splitting them is for readability, the other tests fill fail automatically when a previous crashes. Sadly ATM there is not it.runIfOthersWereSuccessful() so we rely on just running it and letting it fail.
2. I think we never name the tests "happy path", that was my point.

2023-10-24 08:40 UTC, slavistan commented on src/modules/attributes/local/LocalAttributeShareInfo.ts
>      requestReference: string
>make serval validate that requestReference or notificationReference must be set

How do I do this?

2023-10-24 08:43 UTC, jkoenig134 commented on src/modules/attributes/local/LocalAttributeShareInfo.ts
>      requestReference: string
can be done with postFrom => see https://github.com/nmshd/cns-consumption/blob/main/src/modules/notifications/local/LocalNotification.ts#L77-L99 for reference

2023-10-24 09:42 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +}
>and where is the class for this

Why do we need a dedicated class for this? It's unclear to me, when you need and don't need a class.

2023-10-24 09:42 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +     */
This was meant as a separator to group together related methods. If you collapse the methods in your editor, the structure / layers of the implementation become visible. That's the purpose of this comment. We could make it stand out more from regular method comments, I guess.

2023-10-24 09:42 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +     */
As above.

2023-10-24 09:42 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +            predecessor.shareInfo.sourceAttribute === undefined
Pointless bikeshedding.

2023-10-24 09:42 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +            successor.shareInfo.sourceAttribute === undefined
Is there a behavioral difference between the two? Otherwise, `var === undefined` is more concise and to be preferred.

2023-10-24 09:42 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +     */
See above.

2023-10-24 09:42 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +    public async updateAttributeUnsafe(id: CoreId, attributeData: Omit<ILocalAttribute, "id">): Promise<void> {
The signature spells out like "update *this* attribute (identified by its id) with *that* data". I personally find it clearer.

2023-10-24 09:42 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +         * javascript's spread operator. */
Ah, good workaround. Will check it out.

2023-10-24 09:42 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +    }
Aren't the names changed by the minifiers/bundlers? See [here](https://stackoverflow.com/a/10314492), there's possibly more complication in using `attribute.constructor.name` than apparent on the surface.

2023-10-24 09:42 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +     * Helpers
Would require modifying the content lib. Would do this afterwards, in a separate PR.

2023-10-24 09:52 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +}
The classes for that are mostly for validation.
I think we should have classes for every Parameter, so - everywhere.

2023-10-24 09:53 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +            predecessor.shareInfo.sourceAttribute === undefined
Nope

2023-10-24 10:02 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +            successor.shareInfo.sourceAttribute === undefined
Ask Thomas, He explained this to us, I think it's ab bit more safe or. 
We use the above method everywhere, and we will use that in your code to. Accept this please.

2023-10-24 10:05 UTC, jkoenig134 commented on test/modules/notifications/attributeSucceeded/AttributeSucceededNotificationItemProcessor.test.ts
> +                /* Run process() and validate its results. */
nope, It's something that will be in the it.

2023-10-24 10:06 UTC, jkoenig134 commented on test/modules/notifications/attributeSucceeded/AttributeSucceededNotificationItemProcessor.test.ts
> +            it("Happy path for a peer shared identity attribute", async function () {
That's your opinion - and my decision. Change that test.

2023-10-24 10:06 UTC, jkoenig134 commented on test/modules/notifications/attributeSucceeded/AttributeSucceededNotificationItemProcessor.test.ts
> +            it("Happy path for a peer shared identity attribute", async function () {
In that discussion time it would be already finished.

2023-10-24 10:09 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +import { AttributeCreatedEvent, AttributeDeletedEvent, SharedAttributeCopyCreatedEvent } from "./events"
Ok, but I don't think that's enough. This event should also be fired if you succeed your own (shared) attribute.

2023-10-24 10:09 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +import { AttributeCreatedEvent, AttributeDeletedEvent, SharedAttributeCopyCreatedEvent } from "./events"
(like we do it with create and so on)

2023-10-24 10:12 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +     */
I think there is a vscode feature for that - special comments that section the code (e.G. letting you collapse the whole section). I thought we are already using it for a controller, but I cant find it. I think we removed it.

2023-10-24 10:13 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +     */
So you want me to jump around to understand what this is for and what section it belongs to?

With this kind of information it will be removed.

2023-10-24 10:14 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +     */
nope, can still be removed.

2023-10-24 10:15 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +    public async updateAttributeUnsafe(id: CoreId, attributeData: Omit<ILocalAttribute, "id">): Promise<void> {
But way harder to use - and way off how our other code looks. So it should be changed.

2023-10-24 10:16 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +    }
Yeah, but if we EVER have our minifier change class names we have bigger problems then this.
All our bundlers are setup to not do this b/c it would break serval completely.

2023-10-24 10:17 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +     * Helpers
check.

2023-10-24 10:52 UTC, J-Gann commented on test/modules/notifications/attributeSucceeded/AttributeSucceededNotificationItemProcessor.test.ts
> +            it("Happy path for a peer shared identity attribute", async function () {
@stnmtz is this true? If yes, questioning Julian's decisions really seems to lead nowhere. We can save a lot of time here.

2023-10-24 11:15 UTC, tnotheis commented on src/modules/attributes/AttributesController.ts
> +            predecessor.shareInfo.sourceAttribute === undefined
> Pointless bikeshedding.

Julian's right here. Comments are the root of all evil. They can get outdated quickly and therefore mislead the reader in the future. Imagine for example someone adds a new line in between the comment and the `if`. Now the comment describes something completely unrelated, and the reader doesn't have a clue what's going on. 

For reference: see book "Clean Code", subchapter "Don’t Use a Comment When You Can Use a Function or a Variable" (page 67). Actually, the whole chapter 4 is about comments and why they are mostly a bad idea.

2023-10-24 11:19 UTC, tnotheis commented on src/modules/attributes/AttributesController.ts
> +     */
Disclaimer: I don't want to say that we need to fix the following right in this PR, but:

In general, if you feel the need to group your code with a comment, this is a strong indicator for bad design. All code in such a "group" probably belongs to a separate class. So you should keep that in mind for future tasks.

2023-10-25 13:32 UTC, slavistan commented on .vscode/settings.json
- [ ] Remove

2023-10-25 13:32 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +import { AttributeCreatedEvent, AttributeDeletedEvent, SharedAttributeCopyCreatedEvent } from "./events"
Events
- Peer Shared Attribute Succeeded (triggered _nicht_ in der Methoden, kommt aus NotItem Prozessor) 
- Own Shared Attribute Succeeded (triggered innerhalb der Methoden)
- Repository Attribute Succeeded (triggered innerhalb der Methoden)

2023-10-25 13:32 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +}
- Typ auslagern in Datei

2023-10-27 07:57 UTC, slavistan commented on src/consumption/CoreErrors.ts
>      public cannotSucceedAttributesWithAParent(parentId: string | CoreId) {
```
    public cannotSucceedPartOfComplexAttribute(parentId: string | CoreId) {
        return new CoreError(
            "error.consumption.attributes.cannotSucceedPartOfComplexAttribute",
            `The attribute you want to succeed is part of a complex attribute (id: ${parentId}), and cannot be succeeded on its own. Instead, succeed the parent which will implicitly succeed all its children.`
        )
    }
```

Besser? :-)

2023-10-30 14:32 UTC, jkoenig134 requested changes

2023-10-30 14:32 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +            successorSource.content.serialize() !== successor.content.serialize()
comparing serialized strings is not the way. What do you think about [lodash's isEqual](https://www.geeksforgeeks.org/lodash-_-isequal-method/?ref=lbp)? (we use this library on many other places, you can and should use it)

2023-10-30 14:32 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +            successorSource.content.serialize() !== successor.content.serialize()
I should add - you compare the objects that result from .toJSON calls and not the instances.

2023-10-30 14:32 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +        /* Peer must not change. */
yeet

2023-10-30 14:32 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +         * successorParams. */
You do this on many other places where you don't explain it. To be consistent either remove this or explain it everywhere.

2023-10-30 14:32 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +         * succeeded as a whole, instead of succeeding the individual parts. */
comments for all ifs.

2023-10-30 14:32 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +         * javascript's spread operator. */
this was resolved but not tackeled.

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                        /* Clean up attributes before each test. */
Don't describe the code, this comment would only make sense if you describe why the code exists
But for this it should be common sense that we need some cleanup to test on a clean db.

so .. yeet ;)

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("should catch if the successor is not linked to predecessor, if succeeds is explicitly set", async function () {
sadly our formatter doesn't do that but I miss a between the two tests.

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("should catch if the successor already has a successor itself", async function () {
newline

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("should catch if the successor has parent", async function () {
newline

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("should catch if the predecessor does not exist", async function () {
newline

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("should catch if the predecessor already has a successor", async function () {
newline

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("should catch if the predecessor has parent", async function () {
newline

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("should catch attempted change of content type", async function () {
newline

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                        expect(validationResult.isError()).to.be.true
we have a custom matcher for validation-results and you should use it everywhere

=> 
```suggestion
                        expect(validationResult).to.be.an.errorValidationResult()
```

the cool thing is that you can also directly check for the error code and message using this matcher. So you should move the next lines content to this.

Same counts for success, there is a matcher `.to.be.a.successfulValidationResult` please use this everywhere too.

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                        ]).to.include((validationResult as ErrorValidationResult).error.code)
I don't get why there are two possible error codes? Typically a test should always return ONE.

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("should catch attempted change of value type", async function () {
newline :)

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                        /* Clean up attributes before each test. */
see above

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                        /* Create a shared attribute copy ... */
createSharedLocalAttributeCopy is the method name

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                        /* Create repository attribute first. */
comment describes what the method name already describes

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                        /* Try to succeed the own shared identity attribute. */
comment describes a block and I am searching hardly where the succession finally happens

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                        /* Clean up attributes before each test. */
see above

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("Repository attribute", async function () {
```suggestion
                    it("should succeed a repository attribute", async function () {
```

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("Repository attribute", async function () {
same for the other test namings. I will not comment everywhere.

tests with `it` should read as a sentence starting with it.

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                        /* ... and succeed it. */
comments

2023-10-30 14:32 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                    it("Own shared identity attribute", async function () {
test naming

2023-10-31 08:56 UTC, slavistan commented on src/modules/attributes/AttributesController.ts
> +         * javascript's spread operator. */
>But I am also fine with the manual approach.

I kept the manual approach.

2023-10-31 08:56 UTC, slavistan commented on test/modules/attributes/AttributesController.test.ts
> +                        ]).to.include((validationResult as ErrorValidationResult).error.code)
I just want to catch attempts of changing the content type, but as far as I can tell, RelationshipAttributes have no value types in common with IdentityAttributes. Thus, if I change the content type I also change the value type (which is also illegal), and the validation detects an error. However, which error is detected first depends on the implementation and I allow it to catch both.

If you can help me construct a RelationshipAttribute and an IdentityAttribute with the same value type, we can get rid of this, though.

2023-10-31 08:59 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +         * javascript's spread operator. */
Still the comment is invalid

2023-10-31 09:12 UTC, jkoenig134 commented on test/modules/requests/IncomingRequestsController.test.ts
> +                    expect(validationResult).to.be.an.errorValidationResult
this does nothing now.

it's a method that has to be called => `expect(validationResult).to.be.an.errorValidationResult("{msg}", "{code}")`.

Please change everywhere.

2023-10-31 09:13 UTC, jkoenig134 commented on test/modules/requests/IncomingRequestsController.test.ts
> +                    expect(validationResult).to.be.an.errorValidationResult
and the other two expects are then obsolete.

2023-10-31 10:15 UTC, merged