Feature/notifications
nmshd/cns-consumption pull request #112
Opened 2023-09-26 13:20 UTC by jkoenig134

2023-09-27 07:23 UTC, J-Gann commented on src/modules/notifications/NotificationsController.ts
> +    public async sent(message: Message): Promise<void> {
"send" statt "sent" als Methodenname?

2023-09-27 07:24 UTC, jkoenig134 commented on src/modules/notifications/NotificationsController.ts
> +    public async sent(message: Message): Promise<void> {
Nope, this is intended. It doesn't send something - instead it will be called after sending a message with a notification.

2023-09-27 07:25 UTC, jkoenig134 commented on src/modules/notifications/NotificationsController.ts
> +    public async sent(message: Message): Promise<void> {
It's similar to the sent function in the OutgoingRequestsController.

2023-10-04 12:11 UTC, slavistan commented on src/modules/notifications/itemProcessors/AbstractNotificationItemProcessor.ts
> +    protected currentIdentityAddress: CoreAddress
Does currentIdentityAddress mean my own enmeshed address? If so, why 'current'? (Implies that it can change). And, can't the address be retrieved from the `accountController`?

2023-10-10 07:11 UTC, jkoenig134 commented on src/consumption/ConsumptionController.ts
> +        return new Map<RequestItemConstructor, RequestItemProcessorConstructor>([
I'd rather use a private static map instead of const. But yeah, sounds like an optimization where we don't need optimization.

2023-10-10 07:33 UTC, slavistan commented on src/consumption/ConsumptionController.ts
> +        return new Map<RequestItemConstructor, RequestItemProcessorConstructor>([
This isn't about optimization but legibility, the code suggests something which isn't there. As the code stands, it suggests that each instantiation of a ConsumptionController _needs_ its own copy of the map, which suggests further that this data structure will be mutated in the future. This isn't the case, as far as I can tell.

2023-10-10 12:09 UTC, jkoenig134 commented on src/consumption/ConsumptionController.ts
> +    private readonly defaultNotificationItemProcessors = new Map<
i made it static on purpose @J-Gann

2023-10-10 12:11 UTC, J-Gann commented on src/consumption/ConsumptionController.ts
> +    private readonly defaultNotificationItemProcessors = new Map<
The static map results in changes to registry being applied to all accounts. Is this also on purpose?

2023-10-10 12:12 UTC, jkoenig134 commented on src/consumption/ConsumptionController.ts
> +    private readonly defaultNotificationItemProcessors = new Map<
that map will not be changed, only loaded

2023-10-10 12:12 UTC, jkoenig134 commented on src/consumption/ConsumptionController.ts
> +    private readonly defaultNotificationItemProcessors = new Map<
if it is changed its wrong.

2023-10-10 12:13 UTC, jkoenig134 commented on test/modules/notifications/NotificationEnd2End.test.ts
> +/* eslint-disable jest/expect-expect */
this should not be excluded @J-Gann

2023-10-10 12:13 UTC, jkoenig134 commented on test/modules/notifications/NotificationEnd2End.test.ts
> +            })
many it's without expects, this is not a pattern we want to use

2023-10-10 12:14 UTC, jkoenig134 commented on test/modules/notifications/NotificationIntegrationTest.test.ts
> +}
this does nothing

2023-10-10 12:25 UTC, J-Gann commented on src/consumption/ConsumptionController.ts
> +    private readonly defaultNotificationItemProcessors = new Map<
The static map is passed to the [NotificationItemProcessorRegistry](https://github.com/nmshd/cns-consumption/blob/55cb98bf382587c33864460e72544a3f41491c5e/src/consumption/ConsumptionController.ts#L114C1-L118C1) where it can be expanded using the [registerProcessor](https://github.com/nmshd/cns-consumption/blob/55cb98bf382587c33864460e72544a3f41491c5e/src/modules/notifications/itemProcessors/NotificationItemProcessorRegistry.ts#L14C18-L14C18) method, making changes to the list of registered processors static.

2023-10-10 12:31 UTC, jkoenig134 commented on src/consumption/ConsumptionController.ts
> +    private readonly defaultNotificationItemProcessors = new Map<
yeah, that's why it was a getter before. Thanks I'll undo that.

2023-10-10 12:34 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/GenericNotificationItemProcessor.ts
> +}
Yeah, for that case please implement the AbstractNotificationItemProcessor, you can remove the GenericNotificationItemProcessor it is not needed for Notifications

2023-10-10 12:39 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/GenericNotificationItemProcessor.ts
> +}
nvm, I did it.

2023-10-10 13:36 UTC, jkoenig134 commented on src/modules/notifications/itemProcessors/AbstractNotificationItemProcessor.ts
> +    }
If something is not able to rollback we should decide that for each item in the processors itself. But never here.

2023-10-11 10:41 UTC, jkoenig134 commented on test/modules/notifications/NotificationEnd2End.test.ts
> +                expect(rLocalNotificationDB).to.be.not.null
check notification status

2023-10-11 11:44 UTC, tnotheis requested changes

2023-10-11 11:44 UTC, tnotheis commented on src/consumption/index.ts
Why was this file deleted?

2023-10-11 11:44 UTC, tnotheis commented on src/modules/notifications/NotificationsController.ts
> +        // 2. send event and then process in the module
Remove TODO comment

2023-10-11 11:44 UTC, tnotheis commented on src/modules/notifications/NotificationsController.ts
> +    private async process(notification: LocalNotification): Promise<void> {
This method should be moved below its last usage.

2023-10-11 11:44 UTC, tnotheis commented on src/modules/notifications/itemProcessors/NotificationItemProcessorRegistry.ts
> +                `There is already a processor registered for '${itemConstructor.name}''. Use 'replaceProcessorForType' if you want to replace it.`
```suggestion
                `There is already a processor registered for '${itemConstructor.name}'. Use 'replaceProcessorForType' if you want to replace it.`
```

2023-10-11 11:44 UTC, tnotheis commented on test/modules/notifications/NotificationEnd2End.test.ts
> +            let sdb: SynchronizedCollection
Bad naming. I have no clue what's inside of these variables

2023-10-11 11:44 UTC, tnotheis commented on test/modules/notifications/NotificationEnd2End.test.ts
> +            })
Isn't there a test for the actual processing of the notification missing?

2023-10-11 11:45 UTC, jkoenig134 commented on src/consumption/index.ts
it causes circular dependencies

2023-10-11 11:50 UTC, jkoenig134 commented on test/modules/notifications/NotificationEnd2End.test.ts
> +            })
any clue how to test this?

2023-10-11 12:19 UTC, J-Gann commented on src/modules/notifications/NotificationsController.ts
> +                await processor.process(item)
Events returned by process method should be collected and published once all items were processed without error.

2023-10-11 12:21 UTC, J-Gann commented on src/modules/notifications/NotificationsController.ts
> +            this._log.error(`Error while processing notification ${notification.id}: ${e}`)
Add status "Error" for notification?

2023-10-11 12:38 UTC, jkoenig134 commented on src/modules/notifications/NotificationsController.ts
> +            this._log.error(`Error while processing notification ${notification.id}: ${e}`)
nope, we'll just retry.

2023-10-11 13:04 UTC, slavistan commented on src/modules/notifications/NotificationsController.ts
> +        if (!(message.cache!.content instanceof Notification)) {
Question: Why do we have to read data from the message cache (what is the message cache in the first place) and how do I know that the cache is not undefined?

2023-10-11 13:08 UTC, stnmtz commented on test/modules/notifications/NotificationEnd2End.test.ts
> +            })
Check whether the processor exists in the registry?

2023-10-11 13:09 UTC, slavistan commented on src/modules/notifications/NotificationsController.ts
> +        if (!message.isOwn) throw new Error("Cannot send a Notification from a foreign message.")
`sent()` is executed _after_ the message has been sent, iirc. Thus, any error handling performed here is happening too late. Right?

2023-10-11 13:11 UTC, jkoenig134 commented on src/modules/notifications/NotificationsController.ts
> +        if (!message.isOwn) throw new Error("Cannot send a Notification from a foreign message.")
too late - right. It should also happen before. But that doesn't mean that it's wrong here.

2023-10-11 13:11 UTC, jkoenig134 commented on src/modules/notifications/NotificationsController.ts
> +        if (!message.isOwn) throw new Error("Cannot send a Notification from a foreign message.")
and this also stops to mark a Notification as sent from a wrong message.

2023-10-11 13:15 UTC, jkoenig134 commented on src/modules/notifications/NotificationsController.ts
> +        if (!(message.cache!.content instanceof Notification)) {
This is a good question - but also a general design decision of the whole transport library and should not block this PR.
Please remember this question and add this to our Confluence FAQ, there we can explain it.

2023-10-11 13:32 UTC, slavistan commented on src/modules/notifications/NotificationsController.ts
> +        if (!message.isOwn) throw new Error("Cannot send a Notification from a foreign message.")
Throwing here causes a data mismatch between sender and recipient of the notification. I think we should add the notification to the database, since the recipient does so, too. What do you think?

2023-10-11 13:37 UTC, jkoenig134 commented on src/modules/notifications/NotificationsController.ts
> +        if (!message.isOwn) throw new Error("Cannot send a Notification from a foreign message.")
nope, this only stops the user of the consumption library to misuse this method. I don't think this will happen.

2023-10-11 14:33 UTC, J-Gann submitted a review, later dismissed

2023-10-12 05:29 UTC, tnotheis requested changes

2023-10-12 05:29 UTC, tnotheis commented on src/modules/notifications/NotificationsController.ts
> +                const event = await processor.process(item)
Can't there possibly be multiple events created by the processing of a single notification item?

2023-10-12 05:55 UTC, stnmtz commented on src/modules/notifications/NotificationsController.ts
> +                const event = await processor.process(item)
In theory correct, we cross that bridge when we come to it :)

2023-10-12 06:13 UTC, tnotheis commented on src/modules/notifications/NotificationsController.ts
> +                const event = await processor.process(item)
Just thought it'd be easier to do it now than changing the signature when it is used in several places. But I'm fine with it.

2023-10-12 06:13 UTC, tnotheis submitted a review, later dismissed

2023-10-12 06:20 UTC, stnmtz requested changes
- Sollten wir process() von received() rausziehen?
- await bei checkPrerequisites fehlt

2023-10-12 06:20 UTC, stnmtz commented on src/modules/notifications/NotificationsController.ts
> +                if (!processor.checkPrerequisitesOfIncomingNotificationItem(item)) {
```suggestion
                if (!await processor.checkPrerequisitesOfIncomingNotificationItem(item)) {
```

2023-10-12 06:20 UTC, stnmtz commented on src/modules/notifications/NotificationsController.ts
> +        await this.process(notification)
Ich habe im Test gesehen, dass wir aufgrund der Tatsache, dass wir direkt prozessieren, gar nicht den "Open" Status testen können. Einen Retry können wir so auch schlecht durchführen. Sollten wir ggf. das process() rausziehen, um von außen separat antriggern zu können?

2023-10-12 06:20 UTC, stnmtz commented on test/modules/notifications/NotificationEnd2End.test.ts
> +                expect(rLocalNotification.status).to.equal(LocalNotificationStatus.Completed)
Ich finde es irgendwie komisch, dass wir bei received direkt einen Completed status bekommen - siehe Kommentar oben beim NotificationsController. Auch einen retry könnten wir so nicht durchführen.

2023-10-12 06:52 UTC, jkoenig134 commented on src/modules/notifications/NotificationsController.ts
> +                const event = await processor.process(item)
I see it like Thomas, should be easy to add an array to the signature and consume it if we need it.

2023-10-12 08:25 UTC, slavistan commented on src/modules/notifications/NotificationsController.ts
> +            for (const item of processedItems) {
The `rollback()`s must be called in inverse order.

2023-10-12 08:29 UTC, jkoenig134 commented on src/modules/notifications/NotificationsController.ts
> +            for (const item of processedItems) {
check.

2023-10-12 08:36 UTC, stnmtz submitted a review, later dismissed

2023-10-12 08:46 UTC, slavistan approved these changes

2023-10-12 08:49 UTC, merged