Feature/get versions of attribute
nmshd/cns-consumption pull request #124
Opened 2023-11-17 14:46 UTC by Milena-Czierlinski

2023-11-17 15:10 UTC, jkoenig134 requested changes

2023-11-17 15:10 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +        if (!attribute) return // TODO: should we rather throw an error, if the id doesn't exist (already in getLocalAttribute()?)
no TODO comments in production coding please

2023-11-17 15:10 UTC, jkoenig134 commented on test/modules/attributes/AttributesController.test.ts
> +                expect(allVersions0).to.eql([version2, updatedVersion1, updatedVersion0])
please use the long-form for equality everywhere
```suggestion
                expect(allVersions0).to.equal([version2, updatedVersion1, updatedVersion0])
```

2023-11-17 15:31 UTC, jkoenig134 commented
please do me a favor and replace all `node-version: 18` with `node-version: 20` in github actions yaml files.

2023-11-17 16:09 UTC, Milena-Czierlinski commented on src/modules/attributes/AttributesController.ts
> +        if (!attribute) return // TODO: should we rather throw an error, if the id doesn't exist (already in getLocalAttribute()?)
Yeah, I wanted to ask your opinion on this and then remove it. However, I could also do it in a comment.

2023-11-17 16:11 UTC, Milena-Czierlinski commented on test/modules/attributes/AttributesController.test.ts
> +                expect(allVersions0).to.eql([version2, updatedVersion1, updatedVersion0])
Using the long-form, the test fails, since the compared objects have the same content, but are two different objects.

2023-11-20 09:18 UTC, stnmtz commented on src/modules/attributes/AttributesController.ts
> +        if (!attribute) return // TODO: should we rather throw an error, if the id doesn't exist (already in getLocalAttribute()?)
From my point of view, this should be an error (in contradiction to a getAttribute() function, which can return undefined). Thus the return value should also be only LocalAttribute[].

2023-11-20 09:18 UTC, stnmtz commented on src/modules/attributes/AttributesController.ts
> +        while (attribute!.succeededBy) {
@jkoenig134 I would vote for a safety mechanism here, like a counter and a max of 1000 iterations.

2023-11-20 09:18 UTC, stnmtz commented on src/modules/attributes/AttributesController.ts
> +        while (attribute!.succeededBy) {
Same with the other loop below. Btw: You don't need the ! after attribute.

2023-11-20 09:18 UTC, stnmtz commented on src/modules/attributes/AttributesController.ts
> +        return attributeVersions
From my point of view, we should sort the array before returning.

2023-11-20 09:18 UTC, stnmtz commented on test/modules/attributes/AttributesController.test.ts
> +            it("should return all versions of a possibly succeeded relationship attribute", async function () {
Could you please tests for requesting versions of:
- OwnSharedIdentityAttributes (should return only the versions which were shared to the peer)
- PeerSharedIdentityAttributes (should return only the versions which I received from the peer)
- PeerSharedRelationshipAttributes (should return only the versions which I received from the peer)

2023-11-20 16:19 UTC, Milena-Czierlinski commented on test/modules/attributes/AttributesController.test.ts
> +                expect(allVersions0).to.eql([version2, updatedVersion1, updatedVersion0])
Changed it to deep.equal

2023-11-20 16:20 UTC, Milena-Czierlinski commented on src/modules/attributes/AttributesController.ts
> +        while (attribute!.succeededBy) {
I added the safety counter. The ! seems necessary. Maybe because I alter `attribute`.

2023-11-20 16:26 UTC, Milena-Czierlinski commented on test/modules/attributes/AttributesController.test.ts
> +            it("should return all versions of a possibly succeeded relationship attribute", async function () {
I'm not certain how to test the peer shared versions in the best way, since you only have and can succeed those versions, the peer shared with you, i.e. you don't know about unshared attributes of the peer.

2023-11-20 16:39 UTC, stnmtz commented on test/modules/attributes/AttributesController.test.ts
> +            it("should return all versions of a possibly succeeded relationship attribute", async function () {
Correct, but if you don't know about the shared Attributes, all you can do is get the versions of attributes you know of. What you could test for example is the case, that name1 -> name2 -> name3 -> name4 -> name5 are available at the sender, but only name2 -> name4 are available at a peer (as only name2 and name4 were shared). If the peer now calls getVersionsOfAttribute() with either name2 or name4, it should result in an array with name2 and name4.

2023-11-21 11:40 UTC, stnmtz submitted a review, later dismissed

2023-11-21 11:47 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +        if (attribute) attributeVersions.push(attribute)
```suggestion
       if (!attribute) throw TransportCoreErrors.general.recordNotFound(LocalAttribute)

        const attributeVersions: LocalAttribute[] = [attribute]
        while (attribute?.succeeds && j < 1000) {
            attribute = await this.getLocalAttribute(attribute.succeeds)
            if (!attribute) throw TransportCoreErrors.general.recordNotFound(LocalAttribute, attribute.succeeds.toString());
            
            attributeVersions.push(attribute)
            j++
        }
```

2023-11-21 12:51 UTC, jkoenig134 approved these changes

2023-11-21 12:51 UTC, merged