Feature/add onlyLatestSharedVersionPerPeer in getSharedVersionsOfRepositoryAttribute
nmshd/cns-consumption pull request #130
Opened 2023-12-14 13:53 UTC by Milena-Czierlinski

Moreover, delete getSharedCopiesOfRepositoryAttribute, since we discussed that the functionality is so easy that we don't need an extra helper function.

2023-12-18 12:19 UTC, Milena-Czierlinski commented
@stnmtz Should we perhaps change the name from `onlyLatestSharedVersionPerPeer` to just `onlyLatestVersions`, such that it matches the naming of the corresponding parameter in the other use cases (when adjusting the GetSharedVersionsOfIdentityAttribute use case), even if we are less precise then?

2023-12-18 16:57 UTC, stnmtz reviewed
Just the comment for $containsAny -> might this be the cause that ferretdb builds break?

2023-12-18 16:57 UTC, stnmtz commented on src/modules/attributes/AttributesController.ts
> +            query["shareInfo.peer"] = { $containsAny: peers.map((x) => x.toString()) }
Do you mean $in?
I don't know if $containsAny is supported by our database abstraction layer. Looking at https://github.com/js-soft/ts-documentdb-access/tree/main/packages/querytranslator it is not.
@jkoenig134 could you please check?

2023-12-18 17:02 UTC, Milena-Czierlinski commented on src/modules/attributes/AttributesController.ts
> +            query["shareInfo.peer"] = { $containsAny: peers.map((x) => x.toString()) }
@jkoenig134 Asked me to change $in to $containsAny.

Moreover, we were able to fix the ferretdb build by explicitly waiting for an event.

2023-12-18 17:17 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +            query["shareInfo.peer"] = { $containsAny: peers.map((x) => x.toString()) }
I'll recheck our db impls tomorrow.

2023-12-19 07:06 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +            query["shareInfo.peer"] = { $containsAny: peers.map((x) => x.toString()) }
Oh, I mixed something up!

- `$contains` means `db has ["a","b","c"] -> $contains with "a" = true`
   so it checks if an array contains a value of a string contains a substring.
- `$in` means `db has "a" -> $in with ["a","b","c"] = true`
   it checks if any of the query values matches the db value.

I think this works by accident because it also does a string match for every contains value.

So Thomas is right - this must be changed to `$in`.
@Milena-Czierlinski could you please check if you have used `$containsAny` anywhere else?

2023-12-19 07:27 UTC, stnmtz commented on src/modules/attributes/AttributesController.ts
> +            query["shareInfo.peer"] = { $containsAny: peers.map((x) => x.toString()) }
@jkoenig134 could you please add containsAny in the overview ob db query translator?

2023-12-19 07:28 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +            query["shareInfo.peer"] = { $containsAny: peers.map((x) => x.toString()) }
it is. on multiple places

2023-12-19 08:03 UTC, jkoenig134 requested changes
only one small thing

2023-12-19 08:03 UTC, jkoenig134 commented on src/modules/attributes/AttributesController.ts
> +            query["shareInfo.peer"] = { $in: peers.map((x) => x.toString()) }
naming
```suggestion
            query["shareInfo.peer"] = { $in: peers.map((address) => address.toString()) }
```

2023-12-19 08:13 UTC, jkoenig134 approved these changes

2023-12-19 08:17 UTC, merged