Feature/Succeed complex attributes
nmshd/cns-consumption pull request #134
Opened 2024-01-24 14:13 UTC by Milena-Czierlinski

2024-01-26 08:41 UTC, Milena-Czierlinski commented on test/modules/attributes/AttributesController.test.ts
> +                            recipient: "ARecipient",
The value type of `recipient` is just a string. For all other properties, a dedicated child attribute is created, but for `recipient` not. Thus, we can't execute the tests for the child attributes (iterating over `versionXOfChildValues`) for `recipient`.

2024-01-26 08:42 UTC, sebbi08 commented on test/modules/attributes/AttributesController.test.ts
> +                            recipient: "ARecipient",
understand

2024-01-26 08:45 UTC, jkoenig134 requested changes
blocking merge until monday

2024-01-30 15:51 UTC, Milena-Czierlinski commented
Continued in https://github.com/nmshd/runtime/pull/7

2024-01-30 15:51 UTC, closed without merging