Feature/jssnmshdd 2852 new consumption requests
nmshd/cns-consumption pull request #18
Opened 2022-04-21 06:41 UTC by tnotheis

2022-04-21 08:02 UTC, jkoenig134 requested changes

2022-04-21 08:02 UTC, jkoenig134 commented on test/Test.ts
> +use(chaiExclude)
das würde ich in den test-files machen wo es gebraucht wird - machen wir soweit ich weiß schon ein paar mal so

2022-04-21 08:02 UTC, jkoenig134 commented on test/core/TestUtil.ts
> +// import { RelationshipCreationChangeRequestBody, RelationshipTemplateBody } from "@nmshd/content"
warum die auskommentierten imports?

2022-04-21 12:42 UTC, tnotheis commented on src/modules/requests/incoming/IncomingRequestsController.ts
> +            isOwn: this.parent.accountController.identity.isMe(message.cache!.createdBy),
Hab's jetzt noch einfacher gemacht: infoFromSource hat jetzt kein isOwn mehr, weil es ist im Falle eines IncomingRequests ja immer false. Ich prüfe ja vorher sogar noch, ob message.isOwn true ist und throwe wenn nicht. :D Also das war einfach nur unnötig. ;-)

2022-04-21 12:53 UTC, tnotheis commented on test/Test.ts
> +use(chaiExclude)
Hab gerade gemerkt, dass ich das gar nicht (mehr) verwende. Hab das package wieder deinstalliert und alle Referenzen entfernt.

2022-04-21 12:59 UTC, tnotheis commented on src/modules/requests/local/ConsumptionRequestStatus.ts
> +    // Error = "Error",
Hm. Den hab ich ganz vergessen. In diesen Status sollten ja eigentlich Requests wandern, die "aus irgendeinem Grund" nicht prozessiert werden können. Aber wir haben das noch nicht weiter spezifiziert. Würde ich mal auf eine nächste Iteration schieben.

2022-04-21 12:59 UTC, tnotheis commented on src/modules/requests/local/ConsumptionRequestStatus.ts
> +    // Error = "Error",
Ich hab die Zeile komplett entfernt, und im Klassendiagramm als "nicht implementiert" gekennzeichnet.

2022-04-21 13:02 UTC, tnotheis commented on src/modules/requests/outgoing/OutgoingRequestsController.ts
> +import { IDatabaseCollection } from "@js-soft/docdb-access-abstractions"
Hm, verstehe ich nicht. Im IncomingRequestsController sind doch nur die Kommentare bzgl. isOwn, und die treffen im OutgoingRequestsController nicht zu, so wie ich das sehe.

2022-04-21 13:03 UTC, tnotheis commented on src/modules/requests/outgoing/OutgoingRequestsController.ts
> +import { IDatabaseCollection } from "@js-soft/docdb-access-abstractions"
Ah, sorry. GitHub hatte die Kommentare aus irgendeinem Grund ausgeblendet.

2022-04-21 13:05 UTC, tnotheis commented on src/modules/requests/incoming/IncomingRequestsController.ts
> +        const requestDoc = await this.consumptionRequests.findOne({ id: id.toString(), isOwn: false })
Ich wollte damit sicherstellen, dass nicht ausversehen versucht wird, die ID eines incoming Requests in den OutgoingRequestsController reinzugeben und umgekehrt.

2022-04-21 13:07 UTC, tnotheis commented on src/modules/requests/incoming/DecideRequestParametersValidator.ts
> +            return Result.fail(new ApplicationError("", "Number of items in Request and Response do not match"))
Die Implementierung des Validators ist derzeit nur exemplarisch. Das war ja eigentlich deine Aufgabe gewesen. :) Würde ich mal nach hinten schieben.

2022-04-21 15:07 UTC, stnmtz requested changes

2022-04-22 06:00 UTC, tnotheis commented on test/modules/requests/DecideRequestParamsValidator.test.ts
> +            //     expect(true).to.be.false
Die Tests kommen, sobald es eine Implementierung gibt. Und ich hasse TODOs, deshalb: nein, kein TODO. :) Die Tests waren ursprünglich mal dazu gedacht, Julian ein paar Ideen für Validierungen zu geben. Ich lösche sie jetzt einfach mal.

2022-04-22 06:03 UTC, tnotheis commented on src/modules/requests/local/ConsumptionRequestStatusLogEntry.ts
> +    public data?: object
Ich resolve den Kommentar mal, haben wir ja telefonisch besprochen.

2022-04-22 06:04 UTC, tnotheis commented on src/modules/requests/local/ConsumptionRequestStatus.ts
> +    Completed = "Completed"
Ich resolve den Kommentar mal, haben wir ja telefonisch besprochen.

2022-04-22 06:07 UTC, tnotheis commented on src/modules/requests/local/ConsumptionRequestStatusLogEntry.ts
> +    public data?: object
Ich glaub ich wäre da nicht so einschränkend. Hier reicht meiner Meinung nach auch ein JSON Wrapper. Du willst ja einfach nur irgendwelche Informationen ablegen, und nicht dazu gezwungen werden, dafür auch noch ein Interface, eine Klasse, etc. anzulegen.

2022-04-22 06:09 UTC, tnotheis commented on src/modules/requests/local/ConsumptionRequestStatusLogEntry.ts
> +    @validate({ nullable: true })
Warum nicht? Ein Code könnte ja auch ausreichen.

2022-04-22 06:13 UTC, tnotheis commented on src/modules/requests/outgoing/OutgoingRequestsController.ts
> +        for (let i = 0; i < receivedResponse.items.length; i++) {
Leider nein. Weiter unten hole ich mir mit demselben Index noch die ResponseItems.

2022-04-22 06:13 UTC, tnotheis commented on src/modules/requests/outgoing/OutgoingRequestsController.ts
> +        for (let i = 0; i < responseItems.length; i++) {
Auch hier brauche ich den Index noch an einer anderen Stelle.

2022-04-22 06:24 UTC, tnotheis commented on src/modules/requests/outgoing/createOutgoingRequest/CreateOutgoingRequestParameters.ts
> +    public content: Request
Nope. Die id ist optional.

2022-04-22 06:26 UTC, tnotheis commented on src/modules/requests/itemProcessors/RequestItemProcessorRegistry.ts
> +export class RequestItemProcessorRegistry {
Joa, ist sie nicht. Würdest du sagen, dass das wichtig ist? Wenn ja kann ich sie gerne aufnehmen.

2022-04-22 06:39 UTC, tnotheis commented on src/modules/requests/itemProcessors/GenericRequestItemProcessor.ts
> +            result: ResponseItemResult.Accepted,
AcceptResponseItem erbt von DecideResponseItem. Letzteres definiert `result`. AcceptResponseItem schränkt dann die möglichen Werte auf ' Accepted' ein. Es ist aber weiterhin ein Pflichtfeld. Deshalb muss ich es hier leider übergeben.

2022-04-22 06:39 UTC, tnotheis commented on src/modules/requests/itemProcessors/GenericRequestItemProcessor.ts
> +            result: ResponseItemResult.Rejected,
s.o.

2022-04-22 06:47 UTC, tnotheis commented on src/modules/requests/incoming/DecideRequestParametersValidator.ts
> +export class DecideRequestParametersValidator {
Hatte ich absichtlich rausgelassen, weil es m.M.n. ein Implementierungsdetail ist, was auf Dokumentationsebene nicht wichtig ist. Kann ihn aber gerne noch einfügen.

2022-04-22 06:56 UTC, tnotheis commented on src/modules/requests/itemProcessors/ValidationResult.ts
> +            ? ValidationResult.error("inheritedFromItem", "Some child items have errors.", items)
`inheritedFromItem` war nur eine vorübergehende Lösung. Ich weiß auch nicht, wie man das am besten macht. Evtl. sogar undefined? Oder "erroneousItems"? 
Können wir aber von mir aus auch gerne aufschieben. Brauchen wir ja nicht, um erstmal mit der Entwicklung von Features anzufangen.

2022-04-22 06:59 UTC, tnotheis commented on package.json
>          "@js-soft/docdb-access-loki": "1.0.2",
Ich bin etwas verunsichert. Wenn ich den Branch im PR wechseln möchte, bekomme ich folgende Warnung:

> Some commits from the old base branch may be removed from the timeline, and old review comments may become outdated.

Vor allem der erste Part hört sich böse an. Aber wahrscheinlich verstehe ich ihn ein falsch. Kann ja eigentlich nicht sein, dass Commits vom main Branch gelöscht werden.

2022-04-22 07:28 UTC, tnotheis commented on src/modules/requests/local/ConsumptionRequest.ts
> +    @serialize({ type: String })
War glaub noch von früher, als ich bei einem Fehler rumprobiert hatte, woran es liegt. Habs wieder gelöscht.

2022-04-22 07:55 UTC, tnotheis commented on src/modules/requests/itemProcessors/GenericRequestItemProcessor.ts
> +            result: ResponseItemResult.Accepted,
Möglichkeit: Omit<...> in der from Methode und in der Implementierung dann result fix setzen.

2022-04-22 08:21 UTC, jkoenig134 commented on src/modules/requests/local/ConsumptionRequestStatusLogEntry.ts
> +    @validate({ nullable: true })
was mir hier auffällt ist, dass du in der validierung nullable erlaubst, aber das feld selbst (und im interface) ist es nicht nullable

2022-04-22 08:22 UTC, jkoenig134 commented on src/modules/requests/local/ConsumptionRequestStatusLogEntry.ts
> +    public data?: object
Wenn du hier Serializable(Base) hinschreibst macht der automatisch einen json wrapper aus einem Objekt das nicht von Serializable erbt

2022-04-22 08:23 UTC, tnotheis commented on src/modules/requests/local/ConsumptionRequestStatusLogEntry.ts
> +    public data?: object
Wenn ich `SerializableBase` als Typ nehme, werden bei der Deserialisierung alle Properties rausgeworfen:

```ts
const logEntry = ConsumptionRequestStatusLogEntry.from({
    createdAt: CoreDate.utc(),
    newStatus: ConsumptionRequestStatus.Completed,
    oldStatus: ConsumptionRequestStatus.Decided,
    data: { a: "b" },
    code: "code"
})
```

Im deserialisierten Objekt ist die `data` Property ein leeres Objekt.

2022-04-22 08:24 UTC, jkoenig134 commented on src/modules/requests/local/ConsumptionRequestStatusLogEntry.ts
> +    public data?: object
Ich glaube du musst Serializable nehmen und nicht SerializableBase

2022-04-22 08:28 UTC, tnotheis commented on src/modules/requests/local/ConsumptionRequestStatusLogEntry.ts
> +    public data?: object
Nope, geht auch nicht. Selbes Ergebnis.

2022-04-22 08:34 UTC, tnotheis commented on src/modules/requests/incoming/IncomingRequestsController.ts
> +        this.ensureRequestIsInStatus(
Ich würde es sicherheitshalber mal drin lassen. Nicht dass es irgendwann mal aus canAccept rausfliegt. Sollte zwar eigentlich einen Test dafür geben, aber andererseits ist es ja nur ein simpler Stringvergleich. Schadet also nicht, es drin zu lassen.

2022-04-22 09:42 UTC, tnotheis commented on src/modules/requests/incoming/IncomingRequestsController.ts
> +            throw new Error("Cannot decide own Request")
Ich nehme es mal auf meine Liste mit Punkten für die Zukunft mit auf.

2022-04-22 09:48 UTC, tnotheis commented on src/modules/requests/itemProcessors/GenericRequestItemProcessor.ts
> +            result: ResponseItemResult.Accepted,
Hab ich in die Todoliste aufgenommen.

2022-04-22 09:50 UTC, tnotheis commented on src/modules/requests/itemProcessors/ValidationResult.ts
> +            ? ValidationResult.error("inheritedFromItem", "Some child items have errors.", items)
Hab's in die Todo-Liste aufgenommen.

2022-04-22 09:50 UTC, tnotheis commented on src/modules/requests/local/ConsumptionRequestStatusLogEntry.ts
> +    public data?: object
Thomas hat in Teams geschrieben, dass ich es so lassen soll. Wäre ich auch dafür.

2022-04-22 11:46 UTC, stnmtz approved these changes

2022-04-22 11:47 UTC, jkoenig134 approved these changes

2022-04-22 11:50 UTC, merged