Feature/jssnmshdd 2933 update consumption attribute controller for v2 attributes
nmshd/cns-consumption pull request #30
Opened 2022-05-13 13:01 UTC by Lea-Zim

2022-05-13 13:19 UTC, jkoenig134 requested changes

2022-05-13 13:19 UTC, jkoenig134 commented on test/modules/attributes/Attribute.test.ts
> +                expect(attributesAfterDelete).to.be.of.length(3)
jeder test sollte für sich selbst stehen können (noch laufen wenn man it.only schreibt. Hier erwartest du, dass in anderen Tests Attribute erstellt wurden. Stattdessen solltest du ein Attribut erstellen, dann schauen wie viele es gibt, eines löschen und dann wieder schauen wie viele es gibt. Bitte bei anderen Tests auch auf solche Abhängigkeiten achten.

2022-05-13 13:19 UTC, jkoenig134 commented on test/modules/attributes/Attribute.test.ts
> +                expect(attributesAfterDelete).not.to.have.deep.members([{ id: attributes[0]?.id }])
Der Test ist wie wir es vorhin gesehen haben nicht wirklich aussagekräftig, das hat ja bei den potitivtests (ohne not) nicht geklappt.

2022-05-13 13:19 UTC, jkoenig134 commented on test/modules/attributes/Attribute.test.ts
> +                            value: "Wagner"
`Wagner` könnte `ANewSurname` werden

2022-05-13 14:08 UTC, stnmtz commented on src/modules/attributes/local/ConsumptionAttribute.ts
> +    public override technicalProperties = ["@type", "@context", nameof<ConsumptionAttribute>((r) => r.createdAt)]
warum nicht mehr readonly?
plus succeeds, succeededBy, shareInfo, content

2022-05-13 14:08 UTC, stnmtz commented on src/modules/attributes/local/ConsumptionAttribute.ts
> +    public override userdataProperties = [nameof<ConsumptionAttribute>((r) => r.content)]
warum nicht mehr readonly?

2022-05-13 14:08 UTC, stnmtz commented on src/modules/attributes/local/ConsumptionAttribute.ts
> +// TODO: extend
Ich glaube hier sollte ein TODO JSON hin ?

2022-05-13 14:08 UTC, stnmtz commented on test/modules/attributes/Attribute.test.ts
> +                            value: "Hugo"
Mein geliebter Hugo Becker *schnief

2022-05-13 14:08 UTC, stnmtz commented on test/modules/attributes/Attribute.test.ts
> +                            recipient: "Hugo Becker",
Warum nicht auch AStreet, AHouseNumber, AZipCode? Ich finde wir können ruhig mit "gescheiten" Daten testen?

2022-05-13 16:57 UTC, jkoenig134 commented on src/consumption/ConsumptionErrors.ts
> +            `Attribute with id ${id} already exists. Please use succeed instead.`
`with id '${id}' already`

2022-05-13 17:01 UTC, jkoenig134 requested changes

2022-05-16 06:31 UTC, tnotheis requested changes

2022-05-16 06:31 UTC, tnotheis commented on src/modules/attributes/ConsumptionAttributesController.ts
>      public async createAttribute(attribute: ConsumptionAttribute): Promise<ConsumptionAttribute> {
Jep. Dann kann man auch die Abfrage entfernen, ob die ID bereits existiert.

2022-05-16 06:31 UTC, tnotheis commented on src/modules/attributes/ConsumptionAttributesController.ts
> +        successor: ConsumptionAttribute,
Hier dann auch die `CreateAttributeParams` verwenden, oder vielleicht sogar `SucceedAttributeParams` erstellen.

2022-05-17 06:36 UTC, tnotheis requested changes

2022-05-17 06:36 UTC, tnotheis commented on src/modules/attributes/CreateConsumptionAttributeParams.ts
> +export interface ICreateConsumptionAttributeParams extends ISerializable {
Ich finde, die ICreateConsumptionAttributeParams sollten so aussehen:

```ts
export interface ICreateConsumptionAttributeParams extends ISerializable {
  content: IIdentityAttribute | IRelationshipAttribute,
}
```

* attribute habe ich auf content umbenannt, damit es so heißt wie im ConsumptionAttribute
* succeeds und shareInfo sollten von außen nicht angegeben werden können; das geht nur über die entsprechenden Methoden

2022-05-17 06:36 UTC, tnotheis commented on src/modules/attributes/ConsumptionAttributesController.ts
>          return this.filterCurrent(items)
Ok

2022-05-17 06:36 UTC, tnotheis commented on src/modules/attributes/ConsumptionAttributesController.ts
> +        return await this.createConsumptionAttribute(successor)
Ich würde hier wie Thomas bereits gesagt hat das Attribut eher über `ConsumptionAttribute.from` anlegen, und nicht die öffentliche create-Methode dafür verwenden. Es handelt sich hier ja nicht komplexe Logik, daher ist die Duplizierung kein Problem.

2022-05-17 06:36 UTC, tnotheis commented on src/modules/attributes/ConsumptionAttributesController.ts
> +        const sharedConsumptionAttributeCopy = await this.createConsumptionAttribute(createConsumptionAttributeParams)
Auch hier: stattdessen `ConsumptionAttribute.from` verwenden.

2022-05-17 06:36 UTC, tnotheis commented on src/modules/attributes/ConsumptionAttributesController.ts
> +        return ConsumptionAttribute.from(sharedConsumptionAttributeCopy)
Wieso machst du hier nochmal eine Kopie?

2022-05-17 06:36 UTC, tnotheis commented on src/modules/attributes/ConsumptionAttributesController.ts
> +        const updatedAttribute = await this.attributes.update(current, attribute)
Du kannst stattdessen auch einfach das Attribut zurückgeben, was reingegeben wurde. Sollte ja dasselbe sein, wenn die DB nichts verkackt hat. 😉

2022-05-17 06:36 UTC, tnotheis commented on src/modules/attributes/SuccedConsumptionAttributeParams.ts
> +    validFrom?: ICoreDate
Warum hast du hier nochmal `validFrom`? Das ist doch eigentlich schon im `successorContent`.

2022-05-17 07:28 UTC, Lea-Zim commented on src/modules/attributes/ConsumptionAttributesController.ts
> +    public async getAttributes<TQuery extends AbstractAttributeQuery = AbstractAttributeQuery>(
Habe das im Code angepasst und ist outdated

2022-05-17 08:22 UTC, jkoenig134 commented
version bump fehlt

2022-05-17 11:56 UTC, tnotheis approved these changes

2022-05-17 11:58 UTC, jkoenig134 approved these changes

2022-05-17 11:59 UTC, merged