Feature/jssnmshdd 2933 updates for v2 attributes
nmshd/cns-consumption pull request #34
Opened 2022-05-25 15:44 UTC by Lea-Zim

2022-05-25 15:59 UTC, jkoenig134 requested changes

2022-05-25 15:59 UTC, jkoenig134 commented on package.json
> +        "@js-soft/docdb-querytranslator": "^1.0.1"
sort-package-json

2022-05-25 15:59 UTC, jkoenig134 commented on src/modules/attributes/local/QueryTranslator.ts
> +        [nameof<IIdentityAttributeQuery>((x) => x.tags)]: true,
Ich bin verwirrt, eigentlich sind die query translators in der Runtime. Wieso erlaubst du nicht query:any und machst das wirkliche query parsing in der Runtime?

2022-05-26 10:06 UTC, Lea-Zim commented on src/modules/attributes/local/QueryTranslator.ts
> +        [nameof<IIdentityAttributeQuery>((x) => x.tags)]: true,
Ich finde einen Translator einfach die übersichtlichste Methode, weil man das Konzept schon kennt :)

2022-05-26 10:51 UTC, stnmtz approved these changes

2022-05-30 06:17 UTC, jkoenig134 approved these changes

2022-05-30 06:48 UTC, merged