Feature/update-content-library
nmshd/cns-consumption pull request #67
Opened 2022-09-08 13:01 UTC by tnotheis

2022-09-08 15:36 UTC, stnmtz requested changes

2022-09-08 15:36 UTC, stnmtz commented on src/modules/attributes/LocalAttributesController.ts
> +} from "@nmshd/content/dist/attributes/ThirdPartyRelationshipAttributeQuery"
Import ist falsch

2022-09-08 15:36 UTC, stnmtz commented on src/modules/attributes/local/QueryTranslator.ts
> +import {
Import falsch

2022-09-08 15:36 UTC, stnmtz commented on test/modules/attributes/LocalAttributesController.test.ts
> +                expect(attribute).to.not.exist
Du benutzt hier drei mal customerId und frägst ab, ob das attribut nicht existiert. customerId wird doch über die Tests hinweg persistiert. Knallt der Test (auch) deswegen?

2022-09-08 15:36 UTC, stnmtz commented on test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
> +import { ThirdPartyRelationshipAttributeQuery } from "@nmshd/content/dist/attributes/ThirdPartyRelationshipAttributeQuery"
Falscher import

2022-09-08 15:36 UTC, stnmtz commented on test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
> +                                    valueType: "ProprietaryString",
Du hast jetzt hier die Tests "auskommentiert" um schneller ne lauffähige Version zu haben, richtig?

2022-09-08 16:14 UTC, jkoenig134 commented on src/modules/attributes/LocalAttributesController.ts
> +} from "@nmshd/content/dist/attributes/ThirdPartyRelationshipAttributeQuery"
Omg, das hat bei den Web tests zu sooo komischen Problemen geführt. Wir haben schon gedacht wir haben nen komischen ts serval bug gefunden

2022-09-08 16:36 UTC, merged

2022-09-09 06:17 UTC, jkoenig134 reviewed
2 Kleinigkeiten die ich gefunden habe

2022-09-09 06:17 UTC, jkoenig134 commented on src/consumption/ConsumptionBaseController.ts
> +        return values.map((v) => (type as any).from(v))
Das ist sowohl hier, als auch in der Tansport lib falsch .. richtig wäre `return values.map((v) => (type as any).fromAny(v))` die from Methode ist ja nicht überall definiert.

2022-09-09 06:17 UTC, jkoenig134 commented on src/modules/requests/itemProcessors/utility/validateQuery.ts
> +    if (query instanceof ThirdPartyRelationshipAttributeQuery) {
Die anderen Queries müssen gar nicht validiert werden?