Feature/JSSNMSHDD-3143 respect expiresAt in Request handling
nmshd/cns-consumption pull request #77
Opened 2022-09-21 11:11 UTC by jkoenig134

- Feature/jssnmshdd 2852 new consumption requests (#18)
- Refactor/bump ts serval (#20)
- Feature/inject-additional-RequestItemProcessors-on-initilization (#21)
- Feature/make decide parameters better usable for runtime (#23)
- Feature/replace-decision-with-accept-in-decide-request-parameters (#24)
- Feature/jssnmshdd 2947 validate decide request parameters (#22)
- Feature/query-multiple-incoming-or-outgoing-requests (#25)
- Fix/ids-of-incoming-requests-are-generated-without-cnsreq-prefix (#26)
- Chore/remove unused controllers (#27)
- Core/remove cns prefixes (#28)
- Chore/bump content (#29)
- Fix/correct types for create from relationship creation change (#31)
- Feature/jssnmshdd 2933 update consumption attribute controller for v2 attributes (#30)
- Feature/jssnmshdd 2933 updates for v2 attributes (#32)
- Feature/jssnmshdd 2975 read attribute request item processor (#33)
- Feature/jssnmshdd 2933 updates for v2 attributes (#34)
- Chore/export share info (#35)
- Fix/add params from json (#37)
- Bugfix/correct return values on execute queries (#38)
- Feature/JSSNMSHDD-3022-CreateAttributeRequestItems (#40)
- Feature/jssnmshdd 3034 propose attribute request item processor (#42)
- Feature/JSSNMSHDD-3041-ShareAttributeRequestItemProcessor (#43)
- Feature/change-prefix-from-consumption-to-local (#44)
- Chore/bump content (#45)
- Feature/improve-AcceptReadAttributeRequestItemParameters (#47)
- Refactor/simplify-execution-of-attribute-queries (#48)
- Feature/JSSNMSHDD-3056-use-sourceAttributeId-of-CreateAttributeRequestItem (#49)
- Chore/update content library (#50)
- Fix/property-names-in-AcceptReadAttributeRequestItemParameters-are-not-correct (#51)
- Feature/JSSNMSHDD-3093 improve canAccept in IncomingRequestsController (#52)
- Feature/jssnmshdd 3108 allow only empty string for owner in ProposeAttributeRequestItem (#55)
- Feature/JSSNMSHDD-3104 send events (#53)
- Feature/JSSNMSHDD-3109-allow-only-empty-string-or-sender-address-for-owner-in-CreateAttributeRequestItem (#56)
- Feature/complete request without response source (#57)
- Feature/JSSNMSHDD-3123 specific error codes for can decide (#58)
- Feature/JSSNMSHDD-3126 register ConsentRequestItem with a processor (#59)
- Feature/JSSNMSHDD-3139-split-CreateAttributeRequestItem (#60)
- Feature/JSSNMSHDD-3140 register AuthenticationRequestItem (#61)
- chore: set version to 2.0.0-beta.9
- chore: add Expired Request status
- feat: move request status to Expired on get
- chore: add tests for request expiration
- Refactor/make recipient optional for can create outgoing request item (#62)
- Fix/add missing import (#63)
- Bugfix/jssnmshdd 3162 fix queries (#64)
- Chore/update-content-library (#65)
- Fix/publish event for createPeerLocalAttribute (#66)
- Feature/update-content-library (#67)
- fix: version bump (#68)
- Fix/update-content-library (#69)
- Test/improve-tests-for-CreateAttributeRequestItemProcessor (#70)
- Feature/JSSNMSHDD-3156 AttributeListenerController (#71)
- Feature/JSSNMSHDD-3153 RegisterAttributeListenerRequestItemProcessor (#72)
- Refactor/rename LocalAttributesController to AttributesController (#73)
- Feature/JSSNMSHD-3158 discard outgoing requests (#74)
- Chore/remove RelationshipAttributeQuery from LocalAttributeListener (#75)
- fix/ExecuteThirdPartyRelationshipAttributeQuery returns JSON instead of a LocalAttribute instance (#76)

2022-09-21 12:17 UTC, tnotheis requested changes

2022-09-21 12:17 UTC, tnotheis commented on test/modules/requests/IncomingRequestsController.test.ts
> +                it("returns the Request with status 'Expired' when expiredAt is reached", async function () {
Ich hab eigentlich einen eigenen describe für jede Methode. Du bist hier im describe für getIncomingRequests, rufst aber getIncomingRequest auf

2022-09-21 12:17 UTC, tnotheis commented on test/modules/requests/IncomingRequestsController.test.ts
> +                it("queries the Request with status 'Expired' when expiredAt is reached", async function () {
Ähnlich wie oben: "moves Requests whose expiresAt is reached to status 'Expired'"

2022-09-21 12:17 UTC, tnotheis commented on test/modules/requests/IncomingRequestsController.test.ts
> +                    expect(context!.localRequestsAfterAction![0].status).to.equal(LocalRequestStatus.Expired)
Wtf, wieso steht hier ein expect? Das hat hier ja mal gar nichts zu suchen. :)

2022-09-21 12:17 UTC, tnotheis commented on test/modules/requests/OutgoingRequestsController.test.ts
> +                it("returns the Request with status 'Expired' when expiredAt is reached", async function () {
Für diesen Controller gelten dieselben Kommentare wie für den IncomingRequestsController

2022-09-21 12:29 UTC, jkoenig134 commented on src/modules/requests/incoming/IncomingRequestsController.ts
> +        if (expiryDate.add({ minutes: 5 }).isExpired()) {
Hm, mir fällt hier ein Fehler auf.

Die Response wird erstellt, das andere Gerät ist aber gerade nicht an. Ist der Request denn valide wenn die andere Person geantwortet hat als er noch valide war?

2022-09-21 13:47 UTC, tnotheis commented on test/modules/requests/local/LocalRequest.test.ts
> +
Ich würde vor die Tests-Descriptions jeweils noch den Methodennamen setzen. Oder halt eigene describes pro Methode machen. Weil aktuell hast du
* changes the status
* sets the status to expired when the request is expired

unter dem selben describe.

2022-09-21 13:49 UTC, tnotheis commented on test/modules/requests/testHelpers/TestObjectFactory.ts
> +    public static createLocalRequestWith(
Mach doch die Parameter in ein Objekt und optional. Dann kann man auch nur manche setzen, und das ohne für die anderen `undefined` zu übergeben.

2022-09-21 14:06 UTC, tnotheis commented on test/modules/requests/OutgoingRequestsController.test.ts
>                  it("throws when the Local Request is not in status 'Open'", async function () {
Testtitel auch noch anpassen: "[...] is not in status 'Open' or 'Expired'"

2022-09-22 06:51 UTC, tnotheis requested changes

2022-09-22 06:51 UTC, tnotheis commented on test/modules/requests/OutgoingRequestsController.test.ts
> +                    const incomingMessage = TestObjectFactory.createIncomingIMessage(context.currentIdentity)
Übergib doch expiresAt direkt in die Factory, dann musst du es nicht danach setzen.

2022-09-22 06:51 UTC, tnotheis commented on test/modules/requests/OutgoingRequestsController.test.ts
> +                it("throws when try to complete an expired Request with a Message that was created after the expiry date", async function () {
when tryING

2022-09-22 06:51 UTC, tnotheis commented on test/modules/requests/OutgoingRequestsController.test.ts
> +                    When.iTryToCompleteTheOutgoingRequestWith({ responseSourceObject: incomingMessage })
Hier fehlt irgendwie ein await. Da hab ich scheinbar vergessen, die Methode async zu machen.

2022-09-22 06:51 UTC, tnotheis commented on test/modules/requests/OutgoingRequestsController.test.ts
> +                    const incomingMessage = TestObjectFactory.createIncomingIMessage(context.currentIdentity)
Ich glaube, es wäre leserlicher, wenn du die Message ganz oben erzeugst, sodass die Given, When und Then Schritte ohne Abbruch direkt untereinander stehen.

2022-09-22 06:51 UTC, tnotheis commented on test/modules/requests/OutgoingRequestsController.test.ts
> +                    await When.iGetTheOutgoingRequestWith(outgoingRequest.id)
Ich hatte gerade eine Idee: erstell eine `When.iGetTheOutgoingRequest` Methode, in der `this.context.givenLocalRequest.id` verwendet wird. Dann musst du dir das Ergebnis aus dem Given-Step nicht merken.
Und ändere es auch gleich an allen Stellen, an denen ich es sonst noch so machen wie du hier.

2022-09-22 06:51 UTC, tnotheis commented on test/modules/requests/testHelpers/TestObjectFactory.ts
> +        params.status ??= LocalRequestStatus.Draft
Den Defaultwert kannst du eigentlich auch inline unten bei der Verwendung setzen

2022-09-22 07:22 UTC, tnotheis approved these changes

2022-09-22 07:23 UTC, merged